name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          java-package: 'jdk'
          architecture: 'x64'
          distribution: 'temurin'  # Updated to use Temurin JDK

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
